version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +stable clippy --all-targets

  cov:
    desc: Generates code coverage report
    cmds:
      - cmd: cargo llvm-cov clean
      - cmd: cargo llvm-cov --no-cfg-coverage
      - cmd: cargo llvm-cov report --html
      - cmd: echo -e "\n\e[1;32mOpen coverage report\x3A\e[0m file:///$(pwd)/target/llvm-cov/html/index.html\n"

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo +stable doc --no-deps

  doc-open:
    desc: Generates documentation and opens it in browser
    cmds:
      - cmd: cargo +stable doc --no-deps --open

  doc-priv:
    desc: Generates documentation with private items
    cmds:
      - cmd: cargo +stable doc --no-deps --document-private-items

  doc-priv-open:
    desc: Generates documentation with private items and opens it in browser
    cmds:
      - cmd: cargo +stable doc --no-deps --open --document-private-items

  fmt:
    desc: Runs the code formatter
    cmds:
      - cmd: cargo +stable fmt --all

  musl:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build --release --target=x86_64-unknown-linux-musl

  test:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo +stable test

  testn:
    desc: Runs tests in debug mode using nextest
    cmds:
      - cmd: cargo +stable nextest run --no-fail-fast
